ENCODING = "latin1"
SEP = ";"
CHUNKSIZE = 100_000

COLUNAS_SELECIONADAS = [
    "NU_ANO_CENSO",
    "SG_UF",
    "NO_MUNICIPIO",
    "CO_MUNICIPIO",
    "CO_IES",
    "TP_REDE",
    "TP_MODALIDADE_ENSINO",
    "TP_GRAU_ACADEMICO",
    "TP_ORGANIZACAO_ACADEMICA",
    "IN_CAPITAL",
    "QT_ING_TOTAL",
    "QT_MAT_TOTAL",
    "QT_CONC_TOTAL",
    "QT_SIT_TRANCADA",
    "QT_SIT_DESVINCULADO",
    "QT_SIT_TRANSFERIDO",
    "QT_SIT_FALECIDO",
    "QT_ING_FEM",
    "QT_ING_MASC",
    "QT_MAT_FEM",
    "QT_MAT_MASC",
    "QT_ING_FINANC",
    "QT_MAT_FINANC",
    "QT_CONC_FINANC",
]
